version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: empowerone
      POSTGRES_USER: empowerone
      POSTGRES_PASSWORD: empowerone
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://empowerone:empowerone@db:5432/empowerone
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=1
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A backend_project worker -l info
    environment:
      - DATABASE_URL=postgres://empowerone:empowerone@db:5432/empowerone
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  db-data: